[project]
name = "codecrafters-git-python"
version = "0.1.0"
description = "Build your own Git"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "requests>=2.32.3",
]

[dependency-groups]
dev = []
